-- Questao 09: Procedimento com cursor explicito

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_listar_vendedor';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_listar_vendedor (p_sales_rep_id IN PEDIDOS.SALES_REP_ID%TYPE) IS
  CURSOR c_ped IS
    SELECT ORDER_ID, ORDER_STATUS, ORDER_TOTAL
      FROM PEDIDOS
     WHERE SALES_REP_ID = p_sales_rep_id
     ORDER BY ORDER_ID;
  v_reg c_ped%ROWTYPE;
BEGIN
  OPEN c_ped;
  LOOP
    FETCH c_ped INTO v_reg;
    EXIT WHEN c_ped%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(v_reg.ORDER_ID || ' - status ' || v_reg.ORDER_STATUS || ' - total ' || v_reg.ORDER_TOTAL);
  END LOOP;
  CLOSE c_ped;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_listar_vendedor(153);
  SELECT COUNT(*) INTO v_resultado FROM PEDIDOS WHERE SALES_REP_ID = 153;
  v_resultado := 'Pedidos listados do vendedor 153: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
