-- Question 05: INSERT procedure - new order

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_inserir_pedido';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_inserir_pedido (
  p_order_id     IN PEDIDOS.ORDER_ID%TYPE,
  p_order_date   IN PEDIDOS.ORDER_DATE%TYPE,
  p_order_mode   IN PEDIDOS.ORDER_MODE%TYPE,
  p_customer_id  IN PEDIDOS.CUSTOMER_ID%TYPE,
  p_order_status IN PEDIDOS.ORDER_STATUS%TYPE,
  p_order_total  IN PEDIDOS.ORDER_TOTAL%TYPE
) IS
BEGIN
  INSERT INTO PEDIDOS (ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL)
  VALUES (p_order_id, p_order_date, p_order_mode, p_customer_id, p_order_status, p_order_total);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_inserir_pedido(99001, SYSDATE, 'direct', 101, 0, 500);
  SELECT 'Pedido ' || ORDER_ID || ' inserido' INTO v_resultado FROM PEDIDOS WHERE ORDER_ID = 99001;
  DELETE FROM PEDIDOS WHERE ORDER_ID = 99001;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
