-- Question 10: DEFAULT parameter procedure

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_atualizar_status_padrao';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_atualizar_status_padrao (
  p_order_id     IN PEDIDOS.ORDER_ID%TYPE,
  p_order_status IN PEDIDOS.ORDER_STATUS%TYPE DEFAULT 0
) IS
BEGIN
  UPDATE PEDIDOS SET ORDER_STATUS = p_order_status WHERE ORDER_ID = p_order_id AND ORDER_STATUS <> 4;
  DBMS_OUTPUT.PUT_LINE('Status atualizado para ' || p_order_status);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_atualizar_status_padrao(2459);
  SELECT ORDER_STATUS INTO v_resultado FROM PEDIDOS WHERE ORDER_ID = 2459;
  v_resultado := 'Status apos default PENDING(0): ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
