-- Questao 06: Procedimento UPDATE condicional - nao COMPLETE

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_atualizar_status';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_atualizar_status (
  p_order_id     IN PEDIDOS.ORDER_ID%TYPE,
  p_order_status IN PEDIDOS.ORDER_STATUS%TYPE
) IS
  v_status PEDIDOS.ORDER_STATUS%TYPE;
BEGIN
  SELECT ORDER_STATUS INTO v_status FROM PEDIDOS WHERE ORDER_ID = p_order_id;
  IF v_status <> 4 THEN
    UPDATE PEDIDOS SET ORDER_STATUS = p_order_status WHERE ORDER_ID = p_order_id;
    DBMS_OUTPUT.PUT_LINE('Status atualizado');
  ELSE
    DBMS_OUTPUT.PUT_LINE('Pedido concluido - status nao alterado');
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_atualizar_status(2459, 1);
  v_resultado := 'Procedimento executado para pedido 2459';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
