-- Questao 03: Procedimento OUT - retornar order_total

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_obter_total';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_obter_total (
  p_order_id   IN  PEDIDOS.ORDER_ID%TYPE,
  p_order_total OUT PEDIDOS.ORDER_TOTAL%TYPE
) IS
BEGIN
  SELECT ORDER_TOTAL INTO p_order_total FROM PEDIDOS WHERE ORDER_ID = p_order_id;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE v_tot NUMBER; BEGIN
    prc_obter_total(2459, v_tot);
    v_resultado := 'Total obtido: ' || v_tot;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
