-- Questao 02: Funcao com parametros IN - nome completo

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_nome_completo_q02';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE FUNCTION fn_nome_completo_q02 (
  p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE
) RETURN VARCHAR2 IS
  v_nome_completo VARCHAR2(200);
BEGIN
  SELECT FIRST_NAME || ' ' || LAST_NAME
    INTO v_nome_completo
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = p_employee_id;

  RETURN v_nome_completo;
END;
/

SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE('Nome completo: ' || fn_nome_completo_q02(100));
END;
/
