-- Questao 01: Funcao escalar simples - tempo de casa em anos

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_tempo_casa_q01';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE FUNCTION fn_tempo_casa_q01 (
  p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE
) RETURN NUMBER IS
  v_hire_date FUNCIONARIOS.HIRE_DATE%TYPE;
BEGIN
  SELECT HIRE_DATE
    INTO v_hire_date
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = p_employee_id;

  RETURN FLOOR(MONTHS_BETWEEN(SYSDATE, v_hire_date) / 12);
END;
/

SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE('Tempo de casa (anos): ' || fn_tempo_casa_q01(100));
END;
/
