-- Questao 10: Funcao em clausula SELECT

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_formatar_telefone_q10';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE FUNCTION fn_formatar_telefone_q10 (
  p_phone_number IN FUNCIONARIOS.PHONE_NUMBER%TYPE
) RETURN VARCHAR2 IS
BEGIN
  RETURN REGEXP_REPLACE(p_phone_number, '([0-9]{3})\.([0-9]{3})\.([0-9]{4})', '(\1) \2-\3');
END;
/

SELECT EMPLOYEE_ID,
       PHONE_NUMBER AS telefone_original,
       fn_formatar_telefone_q10(PHONE_NUMBER) AS telefone_formatado
  FROM FUNCIONARIOS
 WHERE ROWNUM <= 5;
