-- Questao 06: Funcao DETERMINISTIC

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_nome_titulo_q06';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE FUNCTION fn_nome_titulo_q06 (
  p_first_name IN FUNCIONARIOS.FIRST_NAME%TYPE,
  p_last_name  IN FUNCIONARIOS.LAST_NAME%TYPE
) RETURN VARCHAR2 DETERMINISTIC IS
BEGIN
  RETURN INITCAP(p_first_name || ' ' || p_last_name);
END;
/

SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE(fn_nome_titulo_q06('john', 'smith'));
END;
/
