-- Questao 04: Funcao com tratamento de excecao

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_salario_q04';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE FUNCTION fn_salario_q04 (
  p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE
) RETURN NUMBER IS
  v_salary FUNCIONARIOS.SALARY%TYPE;
BEGIN
  SELECT SALARY
    INTO v_salary
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = p_employee_id;

  RETURN v_salary;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/

SET SERVEROUTPUT ON;

BEGIN
  DBMS_OUTPUT.PUT_LINE('Salario existente: ' || fn_salario_q04(100));
  DBMS_OUTPUT.PUT_LINE('Salario inexistente: ' || fn_salario_q04(99999));
END;
/
