-- Questao 03: Especificacao e corpo separados - pkg_pedidos

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE pkg_pedidos';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PACKAGE pkg_pedidos IS
  FUNCTION fn_buscar (p_order_id IN PEDIDOS.ORDER_ID%TYPE) RETURN PEDIDOS%ROWTYPE;
END pkg_pedidos;
/
CREATE OR REPLACE PACKAGE BODY pkg_pedidos IS
  FUNCTION fn_buscar (p_order_id IN PEDIDOS.ORDER_ID%TYPE) RETURN PEDIDOS%ROWTYPE IS
    v_reg PEDIDOS%ROWTYPE;
  BEGIN
    SELECT * INTO v_reg FROM PEDIDOS WHERE ORDER_ID = p_order_id;
    RETURN v_reg;
  END;
END pkg_pedidos;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE v_reg PEDIDOS%ROWTYPE := pkg_pedidos.fn_buscar(2459); BEGIN
    v_resultado := 'Pedido ' || v_reg.ORDER_ID || ' total ' || v_reg.ORDER_TOTAL;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
