-- Questao 01: Pacote simples pkg_pedidos

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE pkg_pedidos';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PACKAGE pkg_pedidos IS
  FUNCTION fn_dias_pedido (p_order_id IN NUMBER) RETURN NUMBER;
  PROCEDURE prc_exibir_dias (p_order_id IN NUMBER);
END pkg_pedidos;
/
CREATE OR REPLACE PACKAGE BODY pkg_pedidos IS
  FUNCTION fn_dias_pedido (p_order_id IN NUMBER) RETURN NUMBER IS
    v_data DATE;
  BEGIN
    SELECT ORDER_DATE INTO v_data FROM PEDIDOS WHERE ORDER_ID = p_order_id;
    RETURN TRUNC(SYSDATE - v_data);
  END;
  PROCEDURE prc_exibir_dias (p_order_id IN NUMBER) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Dias desde o pedido: ' || fn_dias_pedido(p_order_id));
  END;
END pkg_pedidos;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  pkg_pedidos.prc_exibir_dias(2459);
  v_resultado := 'Dias: ' || pkg_pedidos.fn_dias_pedido(2459);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
