-- Questao 07: Statement-level UPDATE log

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_UPDATE_STMT PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_func_log_upd_stmt';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LOG_UPDATE_STMT (
  comando   VARCHAR2(20),
  data_exec TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_func_log_upd_stmt
AFTER UPDATE ON FUNCIONARIOS
BEGIN
  INSERT INTO LOG_UPDATE_STMT (comando) VALUES ('UPDATE');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  UPDATE FUNCIONARIOS SET JOB_ID = JOB_ID WHERE DEPARTMENT_ID = 60;
  SELECT COUNT(*) INTO v_resultado FROM LOG_UPDATE_STMT;
  v_resultado := 'Comandos UPDATE registrados: ' || v_resultado;
  ROLLBACK;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
