-- Question 02: AFTER INSERT - audit trail

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUDIT_FUNC_INSERT PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_func_audit_ins';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUDIT_FUNC_INSERT (
  employee_id NUMBER,
  nome        VARCHAR2(200),
  data_ins    TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_func_audit_ins
AFTER INSERT ON FUNCIONARIOS
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_FUNC_INSERT (employee_id, nome)
  VALUES (:NEW.EMPLOYEE_ID, :NEW.FIRST_NAME || ' ' || :NEW.LAST_NAME);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO FUNCIONARIOS (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID)
    VALUES (9911, 'Fabio', 'Nunes', 'fabio@test.com', SYSDATE, 'IT_PROG', 3000, 60);
  SELECT nome INTO v_resultado FROM AUDIT_FUNC_INSERT WHERE employee_id = 9911;
  v_resultado := 'Auditado: ' || v_resultado;
  DELETE FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 9911;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
