-- Questao 09: Compound trigger - validacao salario

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_COMPOUND_SALARY PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_func_compound_salary';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LOG_COMPOUND_SALARY (
  mensagem VARCHAR2(4000),
  data_log TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_func_compound_salary
FOR UPDATE OF SALARY ON FUNCIONARIOS
COMPOUND TRIGGER
  v_total NUMBER := 0;
  BEFORE STATEMENT IS
  BEGIN
    v_total := 0;
  END BEFORE STATEMENT;
  BEFORE EACH ROW IS
  BEGIN
    IF :NEW.SALARY < 3000 THEN
      RAISE_APPLICATION_ERROR(-20031, 'Salario abaixo do minimo 3000');
    END IF;
  END BEFORE EACH ROW;
  AFTER EACH ROW IS
  BEGIN
    v_total := v_total + (:NEW.SALARY - :OLD.SALARY);
  END AFTER EACH ROW;
  AFTER STATEMENT IS
  BEGIN
    INSERT INTO LOG_COMPOUND_SALARY (mensagem)
    VALUES ('Variacao salarial total: ' || v_total);
  END AFTER STATEMENT;
END trg_func_compound_salary;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  UPDATE FUNCIONARIOS SET SALARY = SALARY + 10 WHERE EMPLOYEE_ID IN (100, 101);
  SELECT mensagem INTO v_resultado FROM LOG_COMPOUND_SALARY WHERE ROWNUM = 1 ORDER BY data_log DESC;
  ROLLBACK;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
