-- Questao 03: BEFORE UPDATE - impedir reducao salarial

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_func_no_salary_down';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER trg_func_no_salary_down
BEFORE UPDATE OF SALARY ON FUNCIONARIOS
FOR EACH ROW
BEGIN
  IF :NEW.SALARY < :OLD.SALARY THEN
    RAISE_APPLICATION_ERROR(-20030, 'Reducao de salario nao permitida');
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  BEGIN
    UPDATE FUNCIONARIOS SET SALARY = SALARY - 100 WHERE EMPLOYEE_ID = 100;
  EXCEPTION
    WHEN OTHERS THEN
      v_resultado := 'Validacao OK: ' || SUBSTR(SQLERRM, 1, 80);
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
