-- Question 06: Row trigger - salary history :OLD/:NEW

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE HIST_SALARY_FUNC PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_func_hist_salary';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE HIST_SALARY_FUNC (
  employee_id NUMBER,
  old_salary  NUMBER,
  new_salary  NUMBER,
  data_alt    TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_func_hist_salary
AFTER UPDATE OF SALARY ON FUNCIONARIOS
FOR EACH ROW
BEGIN
  INSERT INTO HIST_SALARY_FUNC (employee_id, old_salary, new_salary)
  VALUES (:OLD.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  UPDATE FUNCIONARIOS SET SALARY = SALARY + 1 WHERE EMPLOYEE_ID = 100;
  SELECT 'De ' || old_salary || ' para ' || new_salary INTO v_resultado
    FROM HIST_SALARY_FUNC WHERE employee_id = 100 AND ROWNUM = 1 ORDER BY data_alt DESC;
  ROLLBACK;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
