-- Questao 08: Sequence para employee_id

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_funcionario';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_func_seq_id';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE seq_funcionario START WITH 9900 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER trg_func_seq_id
BEFORE INSERT ON FUNCIONARIOS
FOR EACH ROW
BEGIN
  IF :NEW.EMPLOYEE_ID IS NULL THEN
    :NEW.EMPLOYEE_ID := seq_funcionario.NEXTVAL;
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO FUNCIONARIOS (FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID)
    VALUES ('Igor', 'Vieira', 'igor@test.com', SYSDATE, 'IT_PROG', 3000, 60);
  SELECT 'ID gerado: ' || EMPLOYEE_ID INTO v_resultado FROM FUNCIONARIOS WHERE EMAIL = 'igor@test.com';
  DELETE FROM FUNCIONARIOS WHERE EMAIL = 'igor@test.com';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
