-- Question 05: INSTEAD OF INSERT on view

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_vw_func_ins';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_func_inserir';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_func_inserir AS
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS nome_completo, EMAIL, SALARY
  FROM FUNCIONARIOS;
/
CREATE OR REPLACE TRIGGER trg_vw_func_ins
INSTEAD OF INSERT ON vw_func_inserir
FOR EACH ROW
DECLARE
  v_space PLS_INTEGER;
BEGIN
  v_space := INSTR(:NEW.nome_completo, ' ');
  INSERT INTO FUNCIONARIOS (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID)
  VALUES (
    :NEW.EMPLOYEE_ID,
    SUBSTR(:NEW.nome_completo, 1, v_space - 1),
    SUBSTR(:NEW.nome_completo, v_space + 1),
    :NEW.EMAIL, SYSDATE, 'IT_PROG', :NEW.SALARY, 60
  );
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO vw_func_inserir (EMPLOYEE_ID, nome_completo, EMAIL, SALARY)
    VALUES (9913, 'Helio Costa', 'helio@test.com', 3000);
  SELECT FIRST_NAME || ' ' || LAST_NAME INTO v_resultado FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 9913;
  v_resultado := 'Inserido via view: ' || v_resultado;
  DELETE FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 9913;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
