-- Question 01: BEFORE INSERT - automatic HIRE_DATE

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_func_hire_date';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER trg_func_hire_date
BEFORE INSERT ON FUNCIONARIOS
FOR EACH ROW
BEGIN
  IF :NEW.HIRE_DATE IS NULL THEN
    :NEW.HIRE_DATE := TRUNC(SYSDATE);
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO FUNCIONARIOS (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, JOB_ID, SALARY, DEPARTMENT_ID)
    VALUES (9910, 'Eva', 'Moraes', 'eva@test.com', 'IT_PROG', 3000, 60);
  SELECT 'HIRE_DATE: ' || TO_CHAR(HIRE_DATE, 'DD/MM/YYYY') INTO v_resultado FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 9910;
  DELETE FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 9910;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
