-- Question 04: AFTER DELETE - deletion log

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_FUNC_DELETE PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_func_log_del';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LOG_FUNC_DELETE (
  employee_id NUMBER,
  nome        VARCHAR2(200),
  usuario     VARCHAR2(128),
  data_del    TIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_func_log_del
AFTER DELETE ON FUNCIONARIOS
FOR EACH ROW
BEGIN
  INSERT INTO LOG_FUNC_DELETE (employee_id, nome, usuario, data_del)
  VALUES (:OLD.EMPLOYEE_ID, :OLD.FIRST_NAME || ' ' || :OLD.LAST_NAME, USER, SYSTIMESTAMP);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO FUNCIONARIOS (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID)
    VALUES (9912, 'Gabi', 'Pires', 'gabi@test.com', SYSDATE, 'IT_PROG', 3000, 60);
  DELETE FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 9912;
  SELECT nome INTO v_resultado FROM LOG_FUNC_DELETE WHERE employee_id = 9912;
  v_resultado := 'Excluido e logado: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
