-- Question 07: BULK COLLECT and FORALL

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_reajuste_lote';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE sp_reajuste_lote (
  p_department_id IN NUMBER,
  p_percentual    IN NUMBER DEFAULT 10
) IS
  TYPE t_ids IS TABLE OF FUNCIONARIOS.EMPLOYEE_ID%TYPE;
  v_ids t_ids;
BEGIN
  SELECT EMPLOYEE_ID BULK COLLECT INTO v_ids
    FROM FUNCIONARIOS WHERE DEPARTMENT_ID = p_department_id;
  FORALL i IN 1 .. v_ids.COUNT
    UPDATE FUNCIONARIOS
       SET SALARY = ROUND(SALARY * (1 + p_percentual / 100), 2)
     WHERE EMPLOYEE_ID = v_ids(i);
  DBMS_OUTPUT.PUT_LINE('Reajuste em lote: ' || v_ids.COUNT || ' funcionario(s)');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  ROLLBACK;
  sp_reajuste_lote(60, 1);
  ROLLBACK;
  v_resultado := 'Reajuste em lote executado para dept 60 (rollback aplicado)';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
