-- Question 02: AUTONOMOUS_TRANSACTION - salary audit

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUDIT_SALARY PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_audit_salary';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUDIT_SALARY (
  employee_id NUMBER,
  old_salary  NUMBER,
  new_salary  NUMBER,
  audit_date  DATE
);
/
CREATE OR REPLACE PROCEDURE sp_audit_salary (
  p_employee_id IN NUMBER,
  p_old_salary  IN NUMBER,
  p_new_salary  IN NUMBER
) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO AUDIT_SALARY VALUES (p_employee_id, p_old_salary, p_new_salary, SYSDATE);
  COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE sp_atualizar_salary_audit (
  p_employee_id IN NUMBER,
  p_new_salary  IN NUMBER
) IS
  v_old NUMBER;
BEGIN
  SELECT SALARY INTO v_old FROM FUNCIONARIOS WHERE EMPLOYEE_ID = p_employee_id FOR UPDATE;
  UPDATE FUNCIONARIOS SET SALARY = p_new_salary WHERE EMPLOYEE_ID = p_employee_id;
  sp_audit_salary(p_employee_id, v_old, p_new_salary);
  ROLLBACK;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  sp_atualizar_salary_audit(100, 3100);
  SELECT COUNT(*) INTO v_resultado FROM AUDIT_SALARY;
  v_resultado := 'Registros de auditoria (autonomo): ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
