-- Questao 06: DBMS_SCHEDULER - aniversariantes de empresa

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_rel_aniversariantes';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE sp_rel_aniversariantes IS
BEGIN
  FOR r IN (
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE
      FROM FUNCIONARIOS
     WHERE EXTRACT(MONTH FROM HIRE_DATE) = EXTRACT(MONTH FROM SYSDATE)
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(r.EMPLOYEE_ID || ' - ' || r.FIRST_NAME || ' ' || r.LAST_NAME);
  END LOOP;
END;
/
BEGIN
  BEGIN DBMS_SCHEDULER.DROP_JOB('JOB_ANIVERSARIANTES'); EXCEPTION WHEN OTHERS THEN NULL; END;
  DBMS_SCHEDULER.CREATE_JOB(
    job_name        => 'JOB_ANIVERSARIANTES',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'SP_REL_ANIVERSARIANTES',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=MONTHLY;BYMONTHDAY=1',
    enabled         => FALSE,
    comments        => 'Relatorio mensal de aniversariantes de empresa'
  );
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  sp_rel_aniversariantes;
  SELECT COUNT(*) INTO v_resultado FROM FUNCIONARIOS
   WHERE EXTRACT(MONTH FROM HIRE_DATE) = EXTRACT(MONTH FROM SYSDATE);
  v_resultado := 'Aniversariantes do mes: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
