-- Questao 10: SAVEPOINT em atualizacoes

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_atualizar_savepoint';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE sp_atualizar_savepoint IS
BEGIN
  UPDATE FUNCIONARIOS SET SALARY = SALARY + 100 WHERE EMPLOYEE_ID = 100;
  SAVEPOINT antes_risco;
  UPDATE FUNCIONARIOS SET SALARY = -1 WHERE EMPLOYEE_ID = 100;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO SAVEPOINT antes_risco;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Etapa arriscada revertida via SAVEPOINT');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  sp_atualizar_savepoint;
  SELECT SALARY INTO v_resultado FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 100;
  v_resultado := 'Salario apos SAVEPOINT: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
