-- Question 08: Schema collection type - batch bonus

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE t_employee_id_list';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_bonus_lote';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TYPE t_employee_id_list AS TABLE OF NUMBER;
/
CREATE OR REPLACE PROCEDURE sp_bonus_lote (
  p_ids        IN t_employee_id_list,
  p_percentual IN NUMBER DEFAULT 10
) IS
BEGIN
  FORALL i IN 1 .. p_ids.COUNT
    UPDATE FUNCIONARIOS
       SET SALARY = ROUND(SALARY * (1 + p_percentual / 100), 2)
     WHERE EMPLOYEE_ID = p_ids(i);
  DBMS_OUTPUT.PUT_LINE('Bonus aplicado a ' || p_ids.COUNT || ' funcionario(s)');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  ROLLBACK;
  sp_bonus_lote(t_employee_id_list(100, 101), 2);
  ROLLBACK;
  v_resultado := 'Bonus em lote aplicado a 2 funcionarios (rollback aplicado)';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
