-- Questao 04: REF CURSOR por departamento

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_funcionarios_depto';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE sp_funcionarios_depto (
  p_department_id IN  NUMBER,
  p_cursor        OUT SYS_REFCURSOR
) IS
BEGIN
  OPEN p_cursor FOR
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
      FROM FUNCIONARIOS
     WHERE DEPARTMENT_ID = p_department_id
     ORDER BY EMPLOYEE_ID;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE
    v_cur SYS_REFCURSOR;
    v_id NUMBER; v_fn VARCHAR2(100); v_ln VARCHAR2(100); v_sal NUMBER;
    v_cnt NUMBER := 0;
  BEGIN
    sp_funcionarios_depto(60, v_cur);
    LOOP
      FETCH v_cur INTO v_id, v_fn, v_ln, v_sal;
      EXIT WHEN v_cur%NOTFOUND;
      v_cnt := v_cnt + 1;
    END LOOP;
    CLOSE v_cur;
    v_resultado := 'Funcionarios dept 60 via REF CURSOR: ' || v_cnt;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
