-- Question 05: Error log table

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_ERROS_FUNC PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_atualizar_com_log';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LOG_ERROS_FUNC (
  codigo_erro NUMBER,
  mensagem    VARCHAR2(4000),
  data_erro   TIMESTAMP
);
/
CREATE OR REPLACE PROCEDURE sp_atualizar_com_log (
  p_employee_id IN NUMBER,
  p_salary      IN NUMBER
) IS
BEGIN
  UPDATE FUNCIONARIOS SET SALARY = p_salary WHERE EMPLOYEE_ID = p_employee_id;
  IF SQL%ROWCOUNT = 0 THEN
    RAISE NO_DATA_FOUND;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    INSERT INTO LOG_ERROS_FUNC VALUES (SQLCODE, SQLERRM, SYSTIMESTAMP);
    COMMIT;
    RAISE;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  BEGIN
    sp_atualizar_com_log(99999, 5000);
  EXCEPTION
    WHEN OTHERS THEN
      SELECT mensagem INTO v_resultado FROM LOG_ERROS_FUNC WHERE ROWNUM = 1 ORDER BY data_erro DESC;
      v_resultado := 'Erro registrado: ' || SUBSTR(v_resultado, 1, 120);
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
