-- Questao 03: Especificacao e corpo separados - pkg_funcionarios

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE pkg_funcionarios';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PACKAGE pkg_funcionarios IS
  FUNCTION fn_buscar (p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE) RETURN FUNCIONARIOS%ROWTYPE;
END pkg_funcionarios;
/
CREATE OR REPLACE PACKAGE BODY pkg_funcionarios IS
  FUNCTION fn_buscar (p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE) RETURN FUNCIONARIOS%ROWTYPE IS
    v_reg FUNCIONARIOS%ROWTYPE;
  BEGIN
    SELECT * INTO v_reg FROM FUNCIONARIOS WHERE EMPLOYEE_ID = p_employee_id;
    RETURN v_reg;
  END;
END pkg_funcionarios;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE v_reg FUNCIONARIOS%ROWTYPE := pkg_funcionarios.fn_buscar(100); BEGIN
    v_resultado := v_reg.FIRST_NAME || ' ' || v_reg.LAST_NAME || ' - salario ' || v_reg.SALARY;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
