-- Question 05: Package cursor - list department employees

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PACKAGE pkg_depto';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PACKAGE pkg_depto IS
  PROCEDURE prc_listar (p_department_id IN NUMBER);
END pkg_depto;
/
CREATE OR REPLACE PACKAGE BODY pkg_depto IS
  CURSOR c_func (p_department_id NUMBER) IS
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM FUNCIONARIOS
     WHERE DEPARTMENT_ID = p_department_id ORDER BY EMPLOYEE_ID;
  PROCEDURE prc_listar (p_department_id IN NUMBER) IS
    v_reg c_func%ROWTYPE;
  BEGIN
    FOR v_reg IN c_func(p_department_id) LOOP
      DBMS_OUTPUT.PUT_LINE(v_reg.EMPLOYEE_ID || ' - ' || v_reg.FIRST_NAME || ' ' || v_reg.LAST_NAME);
    END LOOP;
  END;
END pkg_depto;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  pkg_depto.prc_listar(60);
  SELECT COUNT(*) INTO v_resultado FROM FUNCIONARIOS WHERE DEPARTMENT_ID = 60;
  v_resultado := 'Funcionarios dept 60 listados: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
