-- Questao 03: Trigger BEFORE UPDATE para validacao

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_salary_q03';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE TRIGGER trg_salary_q03
BEFORE UPDATE OF SALARY ON FUNCIONARIOS
FOR EACH ROW
BEGIN
  IF :NEW.SALARY < :OLD.SALARY THEN
    RAISE_APPLICATION_ERROR(-20003, 'Reducao de salario nao permitida.');
  END IF;
END;
/

SET SERVEROUTPUT ON;

BEGIN
  UPDATE FUNCIONARIOS SET SALARY = SALARY - 100 WHERE EMPLOYEE_ID = 100;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro esperado: ' || SQLERRM);
END;
/

ROLLBACK;
