-- Questao 01: Trigger BEFORE INSERT

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_pedidos_data_q01';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE TRIGGER trg_pedidos_data_q01
BEFORE INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
  IF :NEW.ORDER_DATE IS NULL THEN
    :NEW.ORDER_DATE := SYSDATE;
  END IF;
END;
/

INSERT INTO PEDIDOS (
  ORDER_ID, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL
) VALUES (
  99991, 'direct', 101, 0, 1000
);

SELECT ORDER_ID, ORDER_DATE FROM PEDIDOS WHERE ORDER_ID = 99991;

ROLLBACK;
