-- Questao 10: Trigger para restringir horario de operacoes

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_horario_q10';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE TRIGGER trg_horario_q10
BEFORE INSERT OR UPDATE OR DELETE ON FUNCIONARIOS
DECLARE
  horario_invalido_exc EXCEPTION;
  PRAGMA EXCEPTION_INIT(horario_invalido_exc, -20010);
  v_hora NUMBER;
  v_dia  NUMBER;
BEGIN
  v_hora := TO_NUMBER(TO_CHAR(SYSDATE, 'HH24'));
  v_dia  := TO_NUMBER(TO_CHAR(SYSDATE, 'D'));

  IF v_dia IN (1, 7) OR v_hora < 8 OR v_hora >= 18 THEN
    RAISE_APPLICATION_ERROR(-20010, 'Operacao permitida apenas em dias uteis, entre 8h e 18h.');
  END IF;
END;
/

SET SERVEROUTPUT ON;

BEGIN
  UPDATE FUNCIONARIOS SET SALARY = SALARY WHERE EMPLOYEE_ID = 100;
  DBMS_OUTPUT.PUT_LINE('Operacao permitida no horario comercial.');
  ROLLBACK;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Operacao bloqueada: ' || SQLERRM);
END;
/
