-- Questao 08: Trigger para geracao automatica de sequence

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_seq_order_q08';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_pedidos_q08';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE SEQUENCE seq_pedidos_q08 START WITH 100000 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_seq_order_q08
BEFORE INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
  IF :NEW.ORDER_ID IS NULL THEN
    :NEW.ORDER_ID := seq_pedidos_q08.NEXTVAL;
  END IF;
END;
/

INSERT INTO PEDIDOS (
  ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL
) VALUES (
  SYSDATE, 'direct', 101, 0, 900
);

SELECT ORDER_ID, ORDER_TOTAL FROM PEDIDOS WHERE ORDER_ID >= 100000 AND ROWNUM = 1;

ROLLBACK;
