-- Questao 05: Trigger INSTEAD OF em view

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_instead_of_q05';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_pedido_funcionario_q05';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE VIEW vw_pedido_funcionario_q05 AS
SELECT p.ORDER_ID,
       p.ORDER_DATE,
       p.ORDER_TOTAL,
       p.SALES_REP_ID,
       f.FIRST_NAME,
       f.LAST_NAME
  FROM PEDIDOS p
  JOIN FUNCIONARIOS f
    ON p.SALES_REP_ID = f.EMPLOYEE_ID;

CREATE OR REPLACE TRIGGER trg_instead_of_q05
INSTEAD OF INSERT ON vw_pedido_funcionario_q05
FOR EACH ROW
BEGIN
  INSERT INTO PEDIDOS (
    ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID,
    ORDER_STATUS, ORDER_TOTAL, SALES_REP_ID
  ) VALUES (
    :NEW.ORDER_ID, NVL(:NEW.ORDER_DATE, SYSDATE), 'direct', 101,
    0, :NEW.ORDER_TOTAL, :NEW.SALES_REP_ID
  );
END;
/

INSERT INTO vw_pedido_funcionario_q05 (
  ORDER_ID, ORDER_TOTAL, SALES_REP_ID, FIRST_NAME, LAST_NAME
) VALUES (
  99988, 3200, 153, 'Representante', 'Teste'
);

SELECT ORDER_ID, ORDER_TOTAL, SALES_REP_ID FROM PEDIDOS WHERE ORDER_ID = 99988;

ROLLBACK;
