-- Questao 05: View com WITH CHECK OPTION

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_funcionarios_depto_q05';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE VIEW vw_funcionarios_depto_q05 AS
SELECT EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       DEPARTMENT_ID,
       SALARY
  FROM FUNCIONARIOS
 WHERE DEPARTMENT_ID = 60
WITH CHECK OPTION;

-- Demonstracao: insercao valida (mesmo departamento)
INSERT INTO vw_funcionarios_depto_q05 (
  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
) VALUES (
  99992, 'Teste', 'Depto60', 60, 8000
);

ROLLBACK;
