-- Questao 03: View com filtro (WHERE)

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_funcionarios_salario_q03';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE VIEW vw_funcionarios_salario_q03 AS
SELECT EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       SALARY
  FROM FUNCIONARIOS
 WHERE SALARY > 10000;

SELECT COUNT(*) AS total_funcionarios FROM vw_funcionarios_salario_q03;
