-- Questao 04: View com agregacao

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_pedidos_por_rep_q04';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE VIEW vw_pedidos_por_rep_q04 AS
SELECT SALES_REP_ID,
       SUM(ORDER_TOTAL) AS total_pedidos,
       AVG(ORDER_TOTAL) AS media_pedidos
  FROM PEDIDOS
 WHERE SALES_REP_ID IS NOT NULL
 GROUP BY SALES_REP_ID;

SELECT * FROM vw_pedidos_por_rep_q04 WHERE ROWNUM <= 5;
