-- Questao 07: View materializada

BEGIN
  EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW mv_pedidos_diario_q07';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE MATERIALIZED VIEW mv_pedidos_diario_q07
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT TRUNC(ORDER_DATE) AS data_pedido,
       COUNT(*) AS qtd_pedidos,
       SUM(ORDER_TOTAL) AS total_pedidos
  FROM PEDIDOS
 GROUP BY TRUNC(ORDER_DATE);

SELECT * FROM mv_pedidos_diario_q07 WHERE ROWNUM <= 5;

EXEC DBMS_MVIEW.REFRESH('MV_PEDIDOS_DIARIO_Q07', 'C');
