-- Questao 09: View com UNION

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_pedidos_status_q09';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE VIEW vw_pedidos_status_q09 AS
SELECT ORDER_ID,
       ORDER_DATE,
       'COMPLETE' AS ORDER_STATUS,
       ORDER_TOTAL,
       'COMPLETE' AS categoria
  FROM PEDIDOS
 WHERE ORDER_STATUS = 4
UNION ALL
SELECT ORDER_ID,
       ORDER_DATE,
       'PENDING' AS ORDER_STATUS,
       ORDER_TOTAL,
       'PENDING' AS categoria
  FROM PEDIDOS
 WHERE ORDER_STATUS = 0;

SELECT * FROM vw_pedidos_status_q09 WHERE ROWNUM <= 5;
