-- Questao 06: View atualizavel vs somente leitura

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_funcionarios_editavel_q06';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_pedidos_agregado_q06';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE VIEW vw_funcionarios_editavel_q06 AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM FUNCIONARIOS;

CREATE OR REPLACE VIEW vw_pedidos_agregado_q06 AS
SELECT SALES_REP_ID, SUM(ORDER_TOTAL) AS total_pedidos
  FROM PEDIDOS
 GROUP BY SALES_REP_ID;

SET SERVEROUTPUT ON;

BEGIN
  UPDATE vw_funcionarios_editavel_q06
     SET SALARY = SALARY
   WHERE EMPLOYEE_ID = 100;
  DBMS_OUTPUT.PUT_LINE('View simples: UPDATE permitido (' || SQL%ROWCOUNT || ' linha(s)).');
  ROLLBACK;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('View simples: ' || SQLERRM);
END;
/

BEGIN
  UPDATE vw_pedidos_agregado_q06
     SET total_pedidos = 0
   WHERE SALES_REP_ID = 153;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('View agregada: UPDATE nao permitido - ' || SQLERRM);
END;
/
