-- Questao 02: View com JOIN

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_pedidos_funcionarios_q02';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE VIEW vw_pedidos_funcionarios_q02 AS
SELECT p.ORDER_ID,
       p.ORDER_DATE,
       p.ORDER_STATUS,
       p.ORDER_TOTAL,
       f.EMPLOYEE_ID,
       f.FIRST_NAME || ' ' || f.LAST_NAME AS nome_representante
  FROM PEDIDOS p
  LEFT JOIN FUNCIONARIOS f
    ON p.SALES_REP_ID = f.EMPLOYEE_ID;

SELECT * FROM vw_pedidos_funcionarios_q02 WHERE ROWNUM <= 5;
