-- Questao 08: View com subquery correlacionada

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_salario_acima_media_q08';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE VIEW vw_salario_acima_media_q08 AS
SELECT f.EMPLOYEE_ID,
       f.FIRST_NAME,
       f.LAST_NAME,
       f.DEPARTMENT_ID,
       f.SALARY
  FROM FUNCIONARIOS f
 WHERE f.SALARY > (
         SELECT AVG(f2.SALARY)
           FROM FUNCIONARIOS f2
          WHERE f2.DEPARTMENT_ID = f.DEPARTMENT_ID
       );

SELECT * FROM vw_salario_acima_media_q08 WHERE ROWNUM <= 5;
