-- Questao 01: View simples

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_funcionarios_resumo_q01';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE VIEW vw_funcionarios_resumo_q01 AS
SELECT EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       JOB_ID
  FROM FUNCIONARIOS;

SELECT * FROM vw_funcionarios_resumo_q01 WHERE ROWNUM <= 5;
