-- Questao 05: INSTEAD OF INSERT em view

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_vw_ped_ins';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_ped_inserir';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_ped_inserir AS
SELECT ORDER_ID, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS,
       ORDER_TOTAL, ORDER_TOTAL * 1.1 AS total_com_taxa
  FROM PEDIDOS;
/
CREATE OR REPLACE TRIGGER trg_vw_ped_ins
INSTEAD OF INSERT ON vw_ped_inserir
FOR EACH ROW
BEGIN
  INSERT INTO PEDIDOS (ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL)
  VALUES (:NEW.ORDER_ID, SYSDATE, :NEW.ORDER_MODE, :NEW.CUSTOMER_ID, :NEW.ORDER_STATUS, :NEW.ORDER_TOTAL);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO vw_ped_inserir (ORDER_ID, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL)
    VALUES (9923, 'direct', 101, 0, 800);
  SELECT 'Pedido ' || ORDER_ID || ' inserido' INTO v_resultado FROM PEDIDOS WHERE ORDER_ID = 9923;
  DELETE FROM PEDIDOS WHERE ORDER_ID = 9923;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
