-- Questao 06: Historico order_status :OLD/:NEW

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE HIST_STATUS_PED PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_ped_hist_status';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE HIST_STATUS_PED (
  order_id    NUMBER,
  old_status  NUMBER,
  new_status  NUMBER,
  data_alt    TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_ped_hist_status
AFTER UPDATE OF ORDER_STATUS ON PEDIDOS
FOR EACH ROW
BEGIN
  INSERT INTO HIST_STATUS_PED (order_id, old_status, new_status)
  VALUES (:OLD.ORDER_ID, :OLD.ORDER_STATUS, :NEW.ORDER_STATUS);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  UPDATE PEDIDOS SET ORDER_STATUS = 1 WHERE ORDER_ID = 2459 AND ORDER_STATUS <> 4;
  SELECT 'Status ' || old_status || ' -> ' || new_status INTO v_resultado
    FROM HIST_STATUS_PED WHERE order_id = 2459 AND ROWNUM = 1 ORDER BY data_alt DESC;
  ROLLBACK;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
