-- Questao 01: BEFORE INSERT - order_date automatico

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_ped_order_date';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER trg_ped_order_date
BEFORE INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
  IF :NEW.ORDER_DATE IS NULL THEN
    :NEW.ORDER_DATE := SYSDATE;
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO PEDIDOS (ORDER_ID, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL)
    VALUES (9920, 'direct', 101, 0, 500);
  SELECT 'ORDER_DATE: ' || TO_CHAR(ORDER_DATE, 'DD/MM/YYYY') INTO v_resultado FROM PEDIDOS WHERE ORDER_ID = 9920;
  DELETE FROM PEDIDOS WHERE ORDER_ID = 9920;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
