-- Question 03: BEFORE UPDATE - prevent ORDER_TOTAL decrease

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_ped_no_total_down';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TRIGGER trg_ped_no_total_down
BEFORE UPDATE OF ORDER_TOTAL ON PEDIDOS
FOR EACH ROW
BEGIN
  IF :NEW.ORDER_TOTAL < :OLD.ORDER_TOTAL THEN
    RAISE_APPLICATION_ERROR(-20033, 'Reducao de order_total nao permitida');
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  BEGIN
    UPDATE PEDIDOS SET ORDER_TOTAL = ORDER_TOTAL - 10 WHERE ORDER_ID = 2459;
  EXCEPTION
    WHEN OTHERS THEN
      v_resultado := 'Validacao OK: ' || SUBSTR(SQLERRM, 1, 80);
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
