-- Question 09: Compound trigger - ORDER_TOTAL validation

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_COMPOUND_TOTAL PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_ped_compound_total';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LOG_COMPOUND_TOTAL (
  mensagem VARCHAR2(4000),
  data_log TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_ped_compound_total
FOR UPDATE OF ORDER_TOTAL ON PEDIDOS
COMPOUND TRIGGER
  v_total NUMBER := 0;
  BEFORE STATEMENT IS
  BEGIN
    v_total := 0;
  END BEFORE STATEMENT;
  BEFORE EACH ROW IS
  BEGIN
    IF :NEW.ORDER_TOTAL < 0 THEN
      RAISE_APPLICATION_ERROR(-20034, 'ORDER_TOTAL negativo nao permitido');
    END IF;
  END BEFORE EACH ROW;
  AFTER EACH ROW IS
  BEGIN
    v_total := v_total + (:NEW.ORDER_TOTAL - :OLD.ORDER_TOTAL);
  END AFTER EACH ROW;
  AFTER STATEMENT IS
  BEGIN
    INSERT INTO LOG_COMPOUND_TOTAL (mensagem)
    VALUES ('Variacao total pedidos: ' || v_total);
  END AFTER STATEMENT;
END trg_ped_compound_total;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  UPDATE PEDIDOS SET ORDER_TOTAL = ORDER_TOTAL + 5 WHERE ORDER_ID = 2459;
  SELECT mensagem INTO v_resultado FROM LOG_COMPOUND_TOTAL WHERE ROWNUM = 1 ORDER BY data_log DESC;
  ROLLBACK;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
