-- Question 08: Sequence for ORDER_ID

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE seq_pedido';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_ped_seq_id';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE SEQUENCE seq_pedido START WITH 99000 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER trg_ped_seq_id
BEFORE INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
  IF :NEW.ORDER_ID IS NULL THEN
    :NEW.ORDER_ID := seq_pedido.NEXTVAL;
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO PEDIDOS (ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL)
    VALUES (SYSDATE, 'direct', 101, 0, 900);
  SELECT 'ID gerado: ' || ORDER_ID INTO v_resultado FROM PEDIDOS WHERE ORDER_TOTAL = 900 AND CUSTOMER_ID = 101
    AND ORDER_ID >= 99000 AND ROWNUM = 1 ORDER BY ORDER_ID DESC;
  DELETE FROM PEDIDOS WHERE ORDER_ID = (SELECT MAX(ORDER_ID) FROM PEDIDOS WHERE ORDER_TOTAL = 900);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
