-- Questao 04: AFTER DELETE - log de exclusao

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_PED_DELETE PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_ped_log_del';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LOG_PED_DELETE (
  order_id  NUMBER,
  total     NUMBER,
  usuario   VARCHAR2(128),
  data_del  TIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_ped_log_del
AFTER DELETE ON PEDIDOS
FOR EACH ROW
BEGIN
  INSERT INTO LOG_PED_DELETE (order_id, total, usuario, data_del)
  VALUES (:OLD.ORDER_ID, :OLD.ORDER_TOTAL, USER, SYSTIMESTAMP);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO PEDIDOS (ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL)
    VALUES (9922, SYSDATE, 'direct', 101, 0, 700);
  DELETE FROM PEDIDOS WHERE ORDER_ID = 9922;
  SELECT 'Pedido ' || order_id || ' excluido' INTO v_resultado FROM LOG_PED_DELETE WHERE order_id = 9922;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
