-- Questao 02: AFTER INSERT - auditoria

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUDIT_PED_INSERT PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_ped_audit_ins';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUDIT_PED_INSERT (
  order_id  NUMBER,
  total     NUMBER,
  data_ins  TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_ped_audit_ins
AFTER INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
  INSERT INTO AUDIT_PED_INSERT (order_id, total) VALUES (:NEW.ORDER_ID, :NEW.ORDER_TOTAL);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO PEDIDOS (ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL)
    VALUES (9921, SYSDATE, 'direct', 101, 0, 600);
  SELECT 'Pedido ' || order_id || ' auditado' INTO v_resultado FROM AUDIT_PED_INSERT WHERE order_id = 9921;
  DELETE FROM PEDIDOS WHERE ORDER_ID = 9921;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
