-- Question 07: Statement-level UPDATE log

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_UPDATE_PED_STMT PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_ped_log_upd_stmt';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LOG_UPDATE_PED_STMT (
  comando   VARCHAR2(20),
  data_exec TIMESTAMP DEFAULT SYSTIMESTAMP
);
/
CREATE OR REPLACE TRIGGER trg_ped_log_upd_stmt
AFTER UPDATE ON PEDIDOS
BEGIN
  INSERT INTO LOG_UPDATE_PED_STMT (comando) VALUES ('UPDATE');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  UPDATE PEDIDOS SET ORDER_STATUS = ORDER_STATUS WHERE CUSTOMER_ID = 101;
  SELECT COUNT(*) INTO v_resultado FROM LOG_UPDATE_PED_STMT;
  v_resultado := 'Comandos UPDATE registrados: ' || v_resultado;
  ROLLBACK;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
