-- Questao 06: PRAGMA EXCEPTION_INIT

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

DECLARE
  fk_violation EXCEPTION;
  PRAGMA EXCEPTION_INIT(fk_violation, -2291);
BEGIN
  INSERT INTO PEDIDOS (
    ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID,
    ORDER_STATUS, ORDER_TOTAL, SALES_REP_ID
  ) VALUES (
    99998, SYSDATE, 'direct', 101,
    'PENDING', 1000, 99999
  );
EXCEPTION
  WHEN fk_violation THEN
    DBMS_OUTPUT.PUT_LINE('Violacao de chave estrangeira: SALES_REP_ID nao existe em FUNCIONARIOS.');
END;
/
