-- Questao 09: DUP_VAL_ON_INDEX

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  INSERT INTO FUNCIONARIOS (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL,
    HIRE_DATE, JOB_ID, SALARY
  ) VALUES (
    100, 'Duplicado', 'Teste', 'duplicado@teste.com',
    SYSDATE, 'IT_PROG', 5000
  );
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    DBMS_OUTPUT.PUT_LINE('EMPLOYEE_ID ja existe. Insercao ignorada.');
END;
/
