-- Questao 05: WHEN OTHERS

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

DECLARE
  v_salary FUNCIONARIOS.SALARY%TYPE;
  v_status PEDIDOS.ORDER_STATUS%TYPE;
BEGIN
  SELECT SALARY
    INTO v_salary
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = 99999;

  UPDATE PEDIDOS
     SET ORDER_STATUS = 'COMPLETE'
   WHERE ORDER_ID = 99999
   RETURNING ORDER_STATUS INTO v_status;

  DBMS_OUTPUT.PUT_LINE('Operacoes concluidas com sucesso.');
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Registro nao encontrado em FUNCIONARIOS ou PEDIDOS.');
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Consulta retornou mais de um registro.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Erro inesperado: ' || SQLCODE || ' - ' || SQLERRM);
END;
/
