-- Questao 01: Tratamento de NO_DATA_FOUND

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

DECLARE
  v_nome FUNCIONARIOS.FIRST_NAME%TYPE;
BEGIN
  SELECT FIRST_NAME
    INTO v_nome
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = 99999;

  DBMS_OUTPUT.PUT_LINE('Funcionario encontrado: ' || v_nome);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Funcionario nao encontrado. Verifique o EMPLOYEE_ID informado.');
END;
/
