-- Questao 08: SQLCODE e SQLERRM

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  UPDATE PEDIDOS
     SET ORDER_TOTAL = 'TEXTO_INVALIDO'
   WHERE ORDER_ID = 2459;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Codigo do erro: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('Mensagem do erro: ' || SQLERRM);
END;
/
