-- Questao 02: Tratamento de TOO_MANY_ROWS

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

DECLARE
  v_nome FUNCIONARIOS.FIRST_NAME%TYPE;
BEGIN
  SELECT FIRST_NAME
    INTO v_nome
    FROM FUNCIONARIOS
   WHERE LAST_NAME = 'King';

  DBMS_OUTPUT.PUT_LINE('Funcionario encontrado: ' || v_nome);
EXCEPTION
  WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('Mais de um funcionario encontrado com o mesmo LAST_NAME. Refine a busca.');
END;
/
