-- Question 03: Boolean function - has commission (FUNCIONARIOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_tem_comissao';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_tem_comissao (p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE)
RETURN NUMBER IS
  v_pct FUNCIONARIOS.COMMISSION_PCT%TYPE;
BEGIN
  SELECT COMMISSION_PCT INTO v_pct
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = p_employee_id;
  RETURN CASE WHEN v_pct IS NOT NULL THEN 1 ELSE 0 END;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := CASE WHEN fn_tem_comissao(145) = 1
    THEN 'Funcionario recebe comissao' ELSE 'Funcionario nao recebe comissao' END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
