-- Questao 05: Funcao com cursor interno - soma salarial por departamento

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_soma_salario_depto';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_soma_salario_depto (p_department_id IN FUNCIONARIOS.DEPARTMENT_ID%TYPE)
RETURN NUMBER IS
  CURSOR c_salarios IS
    SELECT SALARY FROM FUNCIONARIOS WHERE DEPARTMENT_ID = p_department_id;
  v_total NUMBER := 0;
  v_salary FUNCIONARIOS.SALARY%TYPE;
BEGIN
  OPEN c_salarios;
  LOOP
    FETCH c_salarios INTO v_salary;
    EXIT WHEN c_salarios%NOTFOUND;
    v_total := v_total + NVL(v_salary, 0);
  END LOOP;
  CLOSE c_salarios;
  RETURN v_total;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Soma salarial dept 60: ' || fn_soma_salario_depto(60);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
