-- Question 01: Scalar function - tenure in years (FUNCIONARIOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_tempo_casa';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_tempo_casa (p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE)
RETURN NUMBER IS
  v_hire_date FUNCIONARIOS.HIRE_DATE%TYPE;
BEGIN
  SELECT HIRE_DATE INTO v_hire_date
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = p_employee_id;
  RETURN TRUNC(MONTHS_BETWEEN(SYSDATE, v_hire_date) / 12);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Tempo de casa (anos): ' || fn_tempo_casa(100);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
