-- Questao 02: Funcao IN - nome completo (FUNCIONARIOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_nome_completo';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_nome_completo (p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE)
RETURN VARCHAR2 IS
  v_nome VARCHAR2(200);
BEGIN
  SELECT FIRST_NAME || ' ' || LAST_NAME INTO v_nome
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = p_employee_id;
  RETURN v_nome;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Nome completo: ' || fn_nome_completo(100);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
