-- Questao 10: Funcao em clausula SELECT - formatar telefone

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_formatar_telefone';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_formatar_telefone (p_phone IN FUNCIONARIOS.PHONE_NUMBER%TYPE)
RETURN VARCHAR2 IS
BEGIN
  IF p_phone IS NULL THEN
    RETURN 'Sem telefone';
  END IF;
  RETURN '(' || SUBSTR(REPLACE(p_phone, '.', ''), 1, 3) || ') '
    || SUBSTR(REPLACE(p_phone, '.', ''), 4);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

SELECT EMPLOYEE_ID,
       fn_formatar_telefone(PHONE_NUMBER) AS telefone_formatado
  FROM FUNCIONARIOS
 WHERE ROWNUM <= 5;
