-- Questao 08: Funcao que retorna colecao - subordinados diretos

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE t_employee_ids';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_subordinados_diretos';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TYPE t_employee_ids AS TABLE OF NUMBER;
/
CREATE OR REPLACE FUNCTION fn_subordinados_diretos (p_manager_id IN FUNCIONARIOS.MANAGER_ID%TYPE)
RETURN t_employee_ids IS
  v_ids t_employee_ids := t_employee_ids();
BEGIN
  FOR r IN (SELECT EMPLOYEE_ID FROM FUNCIONARIOS WHERE MANAGER_ID = p_manager_id ORDER BY EMPLOYEE_ID) LOOP
    v_ids.EXTEND;
    v_ids(v_ids.COUNT) := r.EMPLOYEE_ID;
  END LOOP;
  RETURN v_ids;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE
    v_ids t_employee_ids := fn_subordinados_diretos(100);
  BEGIN
    v_resultado := 'Subordinados de 100: ' || v_ids.COUNT || ' funcionario(s)';
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
