-- Question 09: Recursive function - subordinate hierarchy count

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_contar_subordinados';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_contar_subordinados (p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE)
RETURN NUMBER IS
  v_total NUMBER := 0;
BEGIN
  FOR r IN (SELECT EMPLOYEE_ID FROM FUNCIONARIOS WHERE MANAGER_ID = p_employee_id) LOOP
    v_total := v_total + 1 + fn_contar_subordinados(r.EMPLOYEE_ID);
  END LOOP;
  RETURN v_total;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Total subordinados (diretos+indiretos) de 100: '
    || fn_contar_subordinados(100);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
