-- Question 07: DEFAULT parameter function - 10% bonus (FUNCIONARIOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_calcular_bonus';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_calcular_bonus (
  p_employee_id      IN FUNCIONARIOS.EMPLOYEE_ID%TYPE,
  p_percentual_bonus IN NUMBER DEFAULT 10
) RETURN NUMBER IS
  v_salary FUNCIONARIOS.SALARY%TYPE;
BEGIN
  SELECT SALARY INTO v_salary FROM FUNCIONARIOS WHERE EMPLOYEE_ID = p_employee_id;
  RETURN ROUND(v_salary * p_percentual_bonus / 100, 2);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Bonus padrao: ' || fn_calcular_bonus(100)
    || ' | bonus 15%: ' || fn_calcular_bonus(100, 15);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
