-- Questao 03: Procedimento com parametro OUT

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_obter_salario_q03';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE PROCEDURE prc_obter_salario_q03 (
  p_employee_id IN  FUNCIONARIOS.EMPLOYEE_ID%TYPE,
  p_salary      OUT FUNCIONARIOS.SALARY%TYPE
) IS
BEGIN
  SELECT SALARY
    INTO p_salary
    FROM FUNCIONARIOS
   WHERE EMPLOYEE_ID = p_employee_id;
END;
/

SET SERVEROUTPUT ON;

DECLARE
  v_salary FUNCIONARIOS.SALARY%TYPE;
BEGIN
  prc_obter_salario_q03(100, v_salary);
  DBMS_OUTPUT.PUT_LINE('Salario retornado: ' || v_salary);
END;
/
