-- Question 08: SQLCODE and SQLERRM

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (ORDEM NUMBER, RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
  v_ordem NUMBER := 1;
BEGIN
  UPDATE FUNCIONARIOS SET SALARY = SALARY WHERE EMPLOYEE_ID = 99999;
EXCEPTION
  WHEN OTHERS THEN
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_ordem, 'SQLCODE: ' || SQLCODE);
    v_ordem := v_ordem + 1;
    INSERT INTO RESULTADO_DEMO VALUES (v_ordem, 'SQLERRM: ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE('SQLCODE: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('SQLERRM: ' || SQLERRM);
END;
/

SELECT ORDEM, RESULTADO FROM RESULTADO_DEMO ORDER BY ORDEM;
