-- Questao 10: Excecao de regra de negocio - COMMISSION_PCT

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE prc_atualizar_comissao (
  p_employee_id    IN FUNCIONARIOS.EMPLOYEE_ID%TYPE,
  p_commission_pct IN FUNCIONARIOS.COMMISSION_PCT%TYPE
) IS
  comissao_invalida_exc EXCEPTION;
BEGIN
  IF p_commission_pct < 0 OR p_commission_pct > 1 THEN
    RAISE comissao_invalida_exc;
  END IF;
  UPDATE FUNCIONARIOS
     SET COMMISSION_PCT = p_commission_pct
   WHERE EMPLOYEE_ID = p_employee_id;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_atualizar_comissao(100, 1.5);
EXCEPTION
  WHEN OTHERS THEN
    v_resultado := 'Comissao fora da faixa valida (0 a 1): ' || SQLERRM;
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
