-- Question 03: User-defined exception - negative salary

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  salario_invalido_exc EXCEPTION;
  v_novo_salary NUMBER := -100;
  v_resultado VARCHAR2(4000);
BEGIN
  IF v_novo_salary < 0 THEN
    RAISE salario_invalido_exc;
  END IF;
  UPDATE FUNCIONARIOS SET SALARY = v_novo_salary WHERE EMPLOYEE_ID = 100;
EXCEPTION
  WHEN salario_invalido_exc THEN
    v_resultado := 'Salario invalido: valor negativo nao permitido.';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
