-- Questao 01: Tratamento de NO_DATA_FOUND (FUNCIONARIOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_nome FUNCIONARIOS.FIRST_NAME%TYPE;
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT FIRST_NAME INTO v_nome FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 99999;
  v_resultado := 'Funcionario encontrado: ' || v_nome;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_resultado := 'Funcionario nao encontrado. Verifique o EMPLOYEE_ID informado.';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
