-- Question 02: TOO_MANY_ROWS handling (FUNCIONARIOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_nome FUNCIONARIOS.LAST_NAME%TYPE;
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT LAST_NAME INTO v_nome FROM FUNCIONARIOS WHERE LAST_NAME = 'Smith';
  v_resultado := 'Unico registro: ' || v_nome;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
EXCEPTION
  WHEN TOO_MANY_ROWS THEN
    v_resultado := 'Mais de um funcionario com o mesmo LAST_NAME. Use chave unica.';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
