-- Questao 06: PRAGMA EXCEPTION_INIT ORA-02291

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  fk_violada_exc EXCEPTION;
  PRAGMA EXCEPTION_INIT(fk_violada_exc, -2291);
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO FUNCIONARIOS (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, MANAGER_ID, DEPARTMENT_ID
  ) VALUES (
    9902, 'FK', 'Teste', 'fk@test.com', SYSDATE, 'IT_PROG', 5000, 88888, 60
  );
EXCEPTION
  WHEN fk_violada_exc THEN
    v_resultado := 'Violacao de chave estrangeira: MANAGER_ID inexistente.';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
