-- Question 05: WHEN OTHERS - multiple operations

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_salary FUNCIONARIOS.SALARY%TYPE;
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT SALARY INTO v_salary FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 99999;
  UPDATE FUNCIONARIOS SET SALARY = SALARY * 1.1 WHERE EMPLOYEE_ID = 100;
  v_resultado := 'Operacoes concluidas.';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_resultado := 'Funcionario nao encontrado (NO_DATA_FOUND).';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  WHEN TOO_MANY_ROWS THEN
    v_resultado := 'Mais de um registro retornado (TOO_MANY_ROWS).';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  WHEN OTHERS THEN
    v_resultado := 'Erro generico: ' || SQLERRM;
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
