-- Questao 02: View com self-join - pedido anterior

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_pedidos_sequencia';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_pedidos_sequencia AS
SELECT p.ORDER_ID, p.CUSTOMER_ID, p.ORDER_DATE,
       LAG(p.ORDER_DATE) OVER (PARTITION BY p.CUSTOMER_ID ORDER BY p.ORDER_DATE) AS pedido_anterior
  FROM PEDIDOS p;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT COUNT(*) INTO v_resultado FROM vw_pedidos_sequencia WHERE pedido_anterior IS NOT NULL;
  v_resultado := 'Pedidos com pedido anterior: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
