-- Question 04: Aggregated view by sales rep

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_total_por_vendedor';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_total_por_vendedor AS
SELECT SALES_REP_ID,
       SUM(ORDER_TOTAL) AS total_pedidos,
       ROUND(AVG(ORDER_TOTAL), 2) AS media_pedidos,
       COUNT(*) AS qtd_pedidos
  FROM PEDIDOS
 WHERE SALES_REP_ID IS NOT NULL
 GROUP BY SALES_REP_ID;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT 'Vendedor ' || SALES_REP_ID || ' total ' || total_pedidos INTO v_resultado
    FROM vw_total_por_vendedor WHERE ROWNUM = 1;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
