-- Question 09: UNION ALL view - order status

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_pedidos_status';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_pedidos_status AS
SELECT ORDER_ID, CUSTOMER_ID, 'COMPLETE' AS status_desc, ORDER_STATUS
  FROM PEDIDOS WHERE ORDER_STATUS = 4
UNION ALL
SELECT ORDER_ID, CUSTOMER_ID, 'PENDING' AS status_desc, ORDER_STATUS
  FROM PEDIDOS WHERE ORDER_STATUS = 0;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT COUNT(*) INTO v_resultado FROM vw_pedidos_status;
  v_resultado := 'Registros na view UNION: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
