-- Question 06: Updatable vs read-only view

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_ped_editavel';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_ped_agregada';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_ped_editavel AS
SELECT ORDER_ID, ORDER_STATUS, ORDER_TOTAL
  FROM PEDIDOS;
/
CREATE OR REPLACE VIEW vw_ped_agregada AS
SELECT CUSTOMER_ID, COUNT(*) AS qtd, SUM(ORDER_TOTAL) AS total
  FROM PEDIDOS
 GROUP BY CUSTOMER_ID;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  UPDATE vw_ped_editavel SET ORDER_STATUS = 0 WHERE ORDER_ID = 2459;
  v_resultado := 'View simples atualizada: ' || SQL%ROWCOUNT || ' linha(s)';
  BEGIN
    UPDATE vw_ped_agregada SET qtd = 1 WHERE CUSTOMER_ID = 101;
  EXCEPTION
    WHEN OTHERS THEN
      v_resultado := v_resultado || ' | View agregada nao atualizavel: ' || SUBSTR(SQLERRM, 1, 80);
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
