-- Questao 03: Funcao booleana - pedido COMPLETE (PEDIDOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_pedido_completo';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_pedido_completo (p_order_id IN PEDIDOS.ORDER_ID%TYPE)
RETURN NUMBER IS
  v_status PEDIDOS.ORDER_STATUS%TYPE;
BEGIN
  SELECT ORDER_STATUS INTO v_status FROM PEDIDOS WHERE ORDER_ID = p_order_id;
  RETURN CASE WHEN v_status = 4 THEN 1 ELSE 0 END;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := CASE WHEN fn_pedido_completo(2459) = 1
    THEN 'Pedido concluido' ELSE 'Pedido nao concluido' END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
