-- Questao 05: Funcao com cursor interno - soma por cliente

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_soma_total_cliente';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_soma_total_cliente (p_customer_id IN PEDIDOS.CUSTOMER_ID%TYPE)
RETURN NUMBER IS
  CURSOR c_pedidos IS
    SELECT ORDER_TOTAL FROM PEDIDOS WHERE CUSTOMER_ID = p_customer_id;
  v_total NUMBER := 0;
  v_valor PEDIDOS.ORDER_TOTAL%TYPE;
BEGIN
  OPEN c_pedidos;
  LOOP
    FETCH c_pedidos INTO v_valor;
    EXIT WHEN c_pedidos%NOTFOUND;
    v_total := v_total + NVL(v_valor, 0);
  END LOOP;
  CLOSE c_pedidos;
  RETURN v_total;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Soma pedidos cliente 101: ' || fn_soma_total_cliente(101);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
