-- Question 02: IN parameter function - status description (PEDIDOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_descricao_status';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_descricao_status (p_order_id IN PEDIDOS.ORDER_ID%TYPE)
RETURN VARCHAR2 IS
  v_status PEDIDOS.ORDER_STATUS%TYPE;
BEGIN
  SELECT ORDER_STATUS INTO v_status FROM PEDIDOS WHERE ORDER_ID = p_order_id;
  RETURN CASE v_status
    WHEN 0 THEN 'Pedido Pendente'
    WHEN 1 THEN 'Pedido Concluido'
    WHEN 2 THEN 'Pedido Enviado'
    WHEN 3 THEN 'Pedido Cancelado'
    WHEN 4 THEN 'Pedido Devolvido'
    ELSE 'Status Desconhecido'
  END;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Descricao: ' || fn_descricao_status(2459);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
