-- Questao 10: Funcao em clausula SELECT - formatar valor monetario

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_formatar_moeda';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_formatar_moeda (p_valor IN NUMBER)
RETURN VARCHAR2 IS
BEGIN
  RETURN 'R$ ' || TO_CHAR(NVL(p_valor, 0), 'FM999G999G990D00', 'NLS_NUMERIC_CHARACTERS='',.''');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

SELECT ORDER_ID,
       fn_formatar_moeda(ORDER_TOTAL) AS total_formatado
  FROM PEDIDOS
 WHERE ROWNUM <= 5;
