-- Questao 01: Funcao escalar - dias desde o pedido (PEDIDOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_dias_desde_pedido';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_dias_desde_pedido (p_order_id IN PEDIDOS.ORDER_ID%TYPE)
RETURN NUMBER IS
  v_order_date PEDIDOS.ORDER_DATE%TYPE;
BEGIN
  SELECT ORDER_DATE INTO v_order_date FROM PEDIDOS WHERE ORDER_ID = p_order_id;
  RETURN TRUNC(SYSDATE - v_order_date);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Dias desde o pedido 2459: ' || fn_dias_desde_pedido(2459);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
