-- Questao 09: Funcao recursiva - comissao por faixas

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_comissao_faixas';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_comissao_faixas (
  p_valor   IN NUMBER,
  p_faixa   IN PLS_INTEGER DEFAULT 1,
  p_limite  IN NUMBER DEFAULT 1000
) RETURN NUMBER IS
  v_base NUMBER;
  v_pct  NUMBER;
BEGIN
  IF p_valor <= 0 THEN
    RETURN 0;
  END IF;
  v_base := LEAST(p_valor, p_limite);
  v_pct  := CASE p_faixa WHEN 1 THEN 0.05 WHEN 2 THEN 0.08 WHEN 3 THEN 0.10 ELSE 0.12 END;
  RETURN ROUND(v_base * v_pct, 2)
    + fn_comissao_faixas(GREATEST(p_valor - p_limite, 0), p_faixa + 1, p_limite);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Comissao recursiva pedido 2459: '
    || fn_comissao_faixas((SELECT ORDER_TOTAL FROM PEDIDOS WHERE ORDER_ID = 2459));
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
