-- Question 07: DEFAULT parameter function - 5% discount (PEDIDOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_aplicar_desconto';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE FUNCTION fn_aplicar_desconto (
  p_order_id           IN PEDIDOS.ORDER_ID%TYPE,
  p_percentual_desconto IN NUMBER DEFAULT 5
) RETURN NUMBER IS
  v_total PEDIDOS.ORDER_TOTAL%TYPE;
BEGIN
  SELECT ORDER_TOTAL INTO v_total FROM PEDIDOS WHERE ORDER_ID = p_order_id;
  RETURN ROUND(v_total * (1 - p_percentual_desconto / 100), 2);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  v_resultado := 'Total com desconto padrao: ' || fn_aplicar_desconto(2459)
    || ' | desconto 10%: ' || fn_aplicar_desconto(2459, 10);
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
