-- Question 08: Collection function - orders by sales rep

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE t_order_ids';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP FUNCTION fn_pedidos_vendedor';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TYPE t_order_ids AS TABLE OF NUMBER;
/
CREATE OR REPLACE FUNCTION fn_pedidos_vendedor (p_sales_rep_id IN PEDIDOS.SALES_REP_ID%TYPE)
RETURN t_order_ids IS
  v_ids t_order_ids := t_order_ids();
BEGIN
  FOR r IN (SELECT ORDER_ID FROM PEDIDOS WHERE SALES_REP_ID = p_sales_rep_id ORDER BY ORDER_ID) LOOP
    v_ids.EXTEND;
    v_ids(v_ids.COUNT) := r.ORDER_ID;
  END LOOP;
  RETURN v_ids;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE
    v_ids t_order_ids := fn_pedidos_vendedor(153);
  BEGIN
    v_resultado := 'Pedidos do vendedor 153: ' || v_ids.COUNT;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
