-- Questao 10: SAVEPOINT em atualizacoes

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_atualizar_ped_savepoint';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE sp_atualizar_ped_savepoint IS
BEGIN
  UPDATE PEDIDOS SET ORDER_TOTAL = ORDER_TOTAL + 10 WHERE ORDER_ID = 2459;
  SAVEPOINT antes_risco;
  UPDATE PEDIDOS SET ORDER_TOTAL = -1 WHERE ORDER_ID = 2459;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK TO SAVEPOINT antes_risco;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Etapa arriscada revertida via SAVEPOINT');
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  sp_atualizar_ped_savepoint;
  SELECT ORDER_TOTAL INTO v_resultado FROM PEDIDOS WHERE ORDER_ID = 2459;
  v_resultado := 'Total apos SAVEPOINT: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
