-- Question 05: Error log table

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOG_ERROS_PED PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_atualizar_ped_com_log';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE LOG_ERROS_PED (
  codigo_erro NUMBER,
  mensagem    VARCHAR2(4000),
  data_erro   TIMESTAMP
);
/
CREATE OR REPLACE PROCEDURE sp_atualizar_ped_com_log (
  p_order_id    IN NUMBER,
  p_order_total IN NUMBER
) IS
BEGIN
  UPDATE PEDIDOS SET ORDER_TOTAL = p_order_total WHERE ORDER_ID = p_order_id;
  IF SQL%ROWCOUNT = 0 THEN
    RAISE NO_DATA_FOUND;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    INSERT INTO LOG_ERROS_PED VALUES (SQLCODE, SQLERRM, SYSTIMESTAMP);
    COMMIT;
    RAISE;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  BEGIN
    sp_atualizar_ped_com_log(99999, 500);
  EXCEPTION
    WHEN OTHERS THEN
      SELECT mensagem INTO v_resultado FROM LOG_ERROS_PED WHERE ROWNUM = 1 ORDER BY data_erro DESC;
      v_resultado := 'Erro registrado: ' || SUBSTR(v_resultado, 1, 120);
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
