-- Questao 06: DBMS_SCHEDULER - arquivar pedidos antigos

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS_ARQUIVO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_arquivar_pedidos';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS_ARQUIVO AS SELECT * FROM PEDIDOS WHERE 1 = 0;
/
CREATE OR REPLACE PROCEDURE sp_arquivar_pedidos IS
  v_corte DATE := ADD_MONTHS(SYSDATE, -24);
BEGIN
  INSERT INTO PEDIDOS_ARQUIVO
  SELECT * FROM PEDIDOS WHERE ORDER_DATE < v_corte;
  DELETE FROM PEDIDOS WHERE ORDER_DATE < v_corte;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Pedidos antigos arquivados');
END;
/
BEGIN
  BEGIN DBMS_SCHEDULER.DROP_JOB('JOB_ARQUIVAR_PEDIDOS'); EXCEPTION WHEN OTHERS THEN NULL; END;
  DBMS_SCHEDULER.CREATE_JOB(
    job_name        => 'JOB_ARQUIVAR_PEDIDOS',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'SP_ARQUIVAR_PEDIDOS',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=DAILY;BYHOUR=2',
    enabled         => FALSE,
    comments        => 'Arquivamento diario de pedidos antigos'
  );
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT COUNT(*) INTO v_resultado FROM PEDIDOS WHERE ORDER_DATE < ADD_MONTHS(SYSDATE, -24);
  v_resultado := 'Pedidos elegiveis para arquivamento: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
