-- Question 02: AUTONOMOUS_TRANSACTION - status audit

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUDIT_STATUS_PED PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_audit_status';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE AUDIT_STATUS_PED (
  order_id   NUMBER,
  old_status NUMBER,
  new_status NUMBER,
  audit_date DATE
);
/
CREATE OR REPLACE PROCEDURE sp_audit_status (
  p_order_id   IN NUMBER,
  p_old_status IN NUMBER,
  p_new_status IN NUMBER
) IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO AUDIT_STATUS_PED VALUES (p_order_id, p_old_status, p_new_status, SYSDATE);
  COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE sp_atualizar_status_audit (
  p_order_id   IN NUMBER,
  p_new_status IN NUMBER
) IS
  v_old NUMBER;
BEGIN
  SELECT ORDER_STATUS INTO v_old FROM PEDIDOS WHERE ORDER_ID = p_order_id FOR UPDATE;
  UPDATE PEDIDOS SET ORDER_STATUS = p_new_status WHERE ORDER_ID = p_order_id;
  sp_audit_status(p_order_id, v_old, p_new_status);
  ROLLBACK;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  sp_atualizar_status_audit(2459, 1);
  SELECT COUNT(*) INTO v_resultado FROM AUDIT_STATUS_PED;
  v_resultado := 'Registros de auditoria (autonomo): ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
