-- Question 08: Schema collection type - cancel orders

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TYPE t_order_id_list';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_cancelar_lote';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE TYPE t_order_id_list AS TABLE OF NUMBER;
/
CREATE OR REPLACE PROCEDURE sp_cancelar_lote (p_ids IN t_order_id_list) IS
BEGIN
  FORALL i IN 1 .. p_ids.COUNT
    UPDATE PEDIDOS SET ORDER_STATUS = 3 WHERE ORDER_ID = p_ids(i);
  DBMS_OUTPUT.PUT_LINE('Pedidos cancelados: ' || p_ids.COUNT);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  ROLLBACK;
  sp_cancelar_lote(t_order_id_list(2459, 2460));
  ROLLBACK;
  v_resultado := 'Cancelamento em lote executado (rollback aplicado)';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
