-- Question 04: REF CURSOR by sales rep

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_pedidos_vendedor';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE sp_pedidos_vendedor (
  p_sales_rep_id IN  NUMBER,
  p_cursor         OUT SYS_REFCURSOR
) IS
BEGIN
  OPEN p_cursor FOR
    SELECT ORDER_ID, ORDER_STATUS, ORDER_TOTAL
      FROM PEDIDOS
     WHERE SALES_REP_ID = p_sales_rep_id
     ORDER BY ORDER_ID;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE
    v_cur SYS_REFCURSOR;
    v_id NUMBER; v_st NUMBER; v_tot NUMBER; v_cnt NUMBER := 0;
  BEGIN
    sp_pedidos_vendedor(153, v_cur);
    LOOP
      FETCH v_cur INTO v_id, v_st, v_tot;
      EXIT WHEN v_cur%NOTFOUND;
      v_cnt := v_cnt + 1;
    END LOOP;
    CLOSE v_cur;
    v_resultado := 'Pedidos vendedor 153 via REF CURSOR: ' || v_cnt;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
