-- Questao 07: BULK COLLECT e FORALL - status pending

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_atualizar_pending_lote';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE sp_atualizar_pending_lote IS
  TYPE t_ids IS TABLE OF PEDIDOS.ORDER_ID%TYPE;
  v_ids t_ids;
BEGIN
  SELECT ORDER_ID BULK COLLECT INTO v_ids
    FROM PEDIDOS WHERE ORDER_STATUS = 0 AND ROWNUM <= 50;
  FORALL i IN 1 .. v_ids.COUNT
    UPDATE PEDIDOS SET ORDER_STATUS = 1 WHERE ORDER_ID = v_ids(i);
  DBMS_OUTPUT.PUT_LINE('Pedidos pending atualizados: ' || v_ids.COUNT);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  ROLLBACK;
  sp_atualizar_pending_lote;
  ROLLBACK;
  v_resultado := 'Atualizacao em lote de pedidos pending (rollback aplicado)';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
