-- Questao 03: EXECUTE IMMEDIATE - contagem distinta

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_contar_distintos_ped';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE sp_contar_distintos_ped (
  p_coluna IN VARCHAR2,
  p_total  OUT NUMBER
) IS
BEGIN
  EXECUTE IMMEDIATE 'SELECT COUNT(DISTINCT ' || p_coluna || ') FROM PEDIDOS' INTO p_total;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE v_total NUMBER; BEGIN
    sp_contar_distintos_ped('CUSTOMER_ID', v_total);
    v_resultado := 'Clientes distintos: ' || v_total;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
