-- Questao 05: Procedimento INSERT - novo funcionario

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_inserir_funcionario';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_inserir_funcionario (
  p_employee_id   IN FUNCIONARIOS.EMPLOYEE_ID%TYPE,
  p_first_name    IN FUNCIONARIOS.FIRST_NAME%TYPE,
  p_last_name     IN FUNCIONARIOS.LAST_NAME%TYPE,
  p_email         IN FUNCIONARIOS.EMAIL%TYPE,
  p_hire_date     IN FUNCIONARIOS.HIRE_DATE%TYPE,
  p_job_id        IN FUNCIONARIOS.JOB_ID%TYPE,
  p_salary        IN FUNCIONARIOS.SALARY%TYPE,
  p_department_id IN FUNCIONARIOS.DEPARTMENT_ID%TYPE
) IS
BEGIN
  INSERT INTO FUNCIONARIOS (
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID
  ) VALUES (
    p_employee_id, p_first_name, p_last_name, p_email, p_hire_date, p_job_id, p_salary, p_department_id
  );
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_inserir_funcionario(9901, 'Ana', 'Silva', 'ana.s@test.com', SYSDATE, 'IT_PROG', 3000, 60);
  SELECT FIRST_NAME || ' ' || LAST_NAME INTO v_resultado FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 9901;
  v_resultado := 'Funcionario inserido: ' || v_resultado;
  DELETE FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 9901;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
