-- Question 09: Explicit cursor procedure

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_listar_depto';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_listar_depto (p_department_id IN FUNCIONARIOS.DEPARTMENT_ID%TYPE) IS
  CURSOR c_func IS
    SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
      FROM FUNCIONARIOS
     WHERE DEPARTMENT_ID = p_department_id
     ORDER BY EMPLOYEE_ID;
  v_reg c_func%ROWTYPE;
BEGIN
  OPEN c_func;
  LOOP
    FETCH c_func INTO v_reg;
    EXIT WHEN c_func%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE(v_reg.EMPLOYEE_ID || ' - ' || v_reg.FIRST_NAME || ' ' || v_reg.LAST_NAME);
  END LOOP;
  CLOSE c_func;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_listar_depto(60);
  SELECT COUNT(*) INTO v_resultado FROM FUNCIONARIOS WHERE DEPARTMENT_ID = 60;
  v_resultado := 'Funcionarios listados no dept 60: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
