-- Question 03: OUT parameter procedure - return salary

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_obter_salario';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_obter_salario (
  p_employee_id IN  FUNCIONARIOS.EMPLOYEE_ID%TYPE,
  p_salary      OUT FUNCIONARIOS.SALARY%TYPE
) IS
BEGIN
  SELECT SALARY INTO p_salary FROM FUNCIONARIOS WHERE EMPLOYEE_ID = p_employee_id;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  DECLARE v_sal NUMBER; BEGIN
    prc_obter_salario(100, v_sal);
    v_resultado := 'Salario obtido: ' || v_sal;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
