-- Questao 10: Procedimento com parametro DEFAULT

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_atualizar_cargo_padrao';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_atualizar_cargo_padrao (
  p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE,
  p_job_id      IN FUNCIONARIOS.JOB_ID%TYPE DEFAULT 'ST_CLERK'
) IS
BEGIN
  UPDATE FUNCIONARIOS SET JOB_ID = p_job_id WHERE EMPLOYEE_ID = p_employee_id;
  DBMS_OUTPUT.PUT_LINE('Cargo atualizado para ' || p_job_id);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_atualizar_cargo_padrao(100);
  SELECT JOB_ID INTO v_resultado FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 100;
  v_resultado := 'Cargo atual (default ST_CLERK): ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
