-- Question 02: IN parameters procedure - new salary message

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_exibir_novo_salario';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_exibir_novo_salario (
  p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE,
  p_salary      IN FUNCIONARIOS.SALARY%TYPE
) IS
BEGIN
  DBMS_OUTPUT.PUT_LINE('Funcionario ' || p_employee_id || ' recebera salario de ' || p_salary);
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  prc_exibir_novo_salario(100, 12000);
  v_resultado := 'Mensagem exibida para funcionario 100 com salario 12000';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
