-- Question 07: Procedure with exception handling and ROLLBACK

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE prc_atualizar_cargo';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE PROCEDURE prc_atualizar_cargo (
  p_employee_id IN FUNCIONARIOS.EMPLOYEE_ID%TYPE,
  p_job_id      IN FUNCIONARIOS.JOB_ID%TYPE
) IS
BEGIN
  UPDATE FUNCIONARIOS SET JOB_ID = p_job_id WHERE EMPLOYEE_ID = p_employee_id;
  IF SQL%ROWCOUNT = 0 THEN
    RAISE NO_DATA_FOUND;
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  BEGIN
    prc_atualizar_cargo(99999, 'IT_PROG');
  EXCEPTION
    WHEN OTHERS THEN
      v_resultado := 'Erro tratado com ROLLBACK: ' || SQLERRM;
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
