-- Question 02: TOO_MANY_ROWS handling (PEDIDOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_status PEDIDOS.ORDER_STATUS%TYPE;
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT ORDER_STATUS INTO v_status FROM PEDIDOS WHERE CUSTOMER_ID = 101;
  v_resultado := 'Unico pedido: ' || v_status;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
EXCEPTION
  WHEN TOO_MANY_ROWS THEN
    v_resultado := 'Mais de um pedido para o mesmo CUSTOMER_ID.';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
