-- Question 08: SQLCODE and SQLERRM

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (ORDEM NUMBER, RESULTADO VARCHAR2(4000));

DECLARE
  v_ordem NUMBER := 1;
BEGIN
  UPDATE PEDIDOS SET ORDER_STATUS = ORDER_STATUS WHERE ORDER_ID = 99999;
EXCEPTION
  WHEN OTHERS THEN
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_ordem, 'SQLCODE: ' || SQLCODE);
    v_ordem := v_ordem + 1;
    INSERT INTO RESULTADO_DEMO VALUES (v_ordem, 'SQLERRM: ' || SQLERRM);
END;
/

SELECT ORDEM, RESULTADO FROM RESULTADO_DEMO ORDER BY ORDEM;
