-- Question 01: NO_DATA_FOUND handling (PEDIDOS)

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_total PEDIDOS.ORDER_TOTAL%TYPE;
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT ORDER_TOTAL INTO v_total FROM PEDIDOS WHERE ORDER_ID = 99999;
  v_resultado := 'Pedido encontrado: ' || v_total;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_resultado := 'Pedido nao encontrado. Verifique o ORDER_ID informado.';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
