-- Question 06: PRAGMA EXCEPTION_INIT ORA-02290

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEDIDOS DROP CONSTRAINT chk_pedidos_total_pos';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

ALTER TABLE PEDIDOS ADD CONSTRAINT chk_pedidos_total_pos CHECK (ORDER_TOTAL >= 0);

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  check_violada_exc EXCEPTION;
  PRAGMA EXCEPTION_INIT(check_violada_exc, -2290);
  v_resultado VARCHAR2(4000);
BEGIN
  INSERT INTO PEDIDOS (
    ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, ORDER_TOTAL, SALES_REP_ID
  ) VALUES (
    99002, SYSDATE, 'direct', 101, 'PENDING', -100, 153
  );
EXCEPTION
  WHEN check_violada_exc THEN
    v_resultado := 'Violacao de check constraint: ORDER_TOTAL negativo.';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
