-- Question 05: WHEN OTHERS - multiple operations

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_total PEDIDOS.ORDER_TOTAL%TYPE;
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT ORDER_TOTAL INTO v_total FROM PEDIDOS WHERE ORDER_ID = 99999;
  UPDATE PEDIDOS SET ORDER_STATUS = 'COMPLETE' WHERE ORDER_ID = 2459;
  v_resultado := 'Operacoes concluidas.';
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    v_resultado := 'Pedido nao encontrado (NO_DATA_FOUND).';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  WHEN TOO_MANY_ROWS THEN
    v_resultado := 'Mais de um registro (TOO_MANY_ROWS).';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  WHEN OTHERS THEN
    v_resultado := 'Erro generico: ' || SQLERRM;
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
