-- Questao 03: Excecao customizada - ORDER_TOTAL negativo

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

SET SERVEROUTPUT ON;


BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  valor_invalido_exc EXCEPTION;
  v_novo_total NUMBER := -500;
  v_resultado VARCHAR2(4000);
BEGIN
  IF v_novo_total < 0 THEN
    RAISE valor_invalido_exc;
  END IF;
  UPDATE PEDIDOS SET ORDER_TOTAL = v_novo_total WHERE ORDER_ID = 2459;
EXCEPTION
  WHEN valor_invalido_exc THEN
    v_resultado := 'Valor invalido: ORDER_TOTAL negativo nao permitido.';
    DELETE FROM RESULTADO_DEMO;
    INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
    DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
