-- Question 09: UNION ALL view - commission flag

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_funcionarios_comissao';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_funcionarios_comissao AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, 'Com comissao' AS tipo, COMMISSION_PCT
  FROM FUNCIONARIOS WHERE COMMISSION_PCT IS NOT NULL
UNION ALL
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, 'Sem comissao' AS tipo, NULL
  FROM FUNCIONARIOS WHERE COMMISSION_PCT IS NULL;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT COUNT(*) INTO v_resultado FROM vw_funcionarios_comissao;
  v_resultado := 'Registros na view UNION: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
