-- Question 06: Updatable vs read-only view

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_func_editavel';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_func_agregada';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_func_editavel AS
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID
  FROM FUNCIONARIOS;
/
CREATE OR REPLACE VIEW vw_func_agregada AS
SELECT DEPARTMENT_ID, COUNT(*) AS qtd, AVG(SALARY) AS media
  FROM FUNCIONARIOS
 GROUP BY DEPARTMENT_ID;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  UPDATE vw_func_editavel SET JOB_ID = 'IT_PROG' WHERE EMPLOYEE_ID = 100;
  v_resultado := 'View simples atualizada: ' || SQL%ROWCOUNT || ' linha(s)';
  BEGIN
    UPDATE vw_func_agregada SET qtd = 1 WHERE DEPARTMENT_ID = 60;
  EXCEPTION
    WHEN OTHERS THEN
      v_resultado := v_resultado || ' | View agregada nao atualizavel: ' || SUBSTR(SQLERRM, 1, 80);
  END;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
