-- Questao 08: View com subquery correlacionada

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_acima_media_depto';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_acima_media_depto AS
SELECT f.EMPLOYEE_ID, f.FIRST_NAME, f.LAST_NAME, f.DEPARTMENT_ID, f.SALARY
  FROM FUNCIONARIOS f
 WHERE f.SALARY > (
   SELECT AVG(SALARY) FROM FUNCIONARIOS WHERE DEPARTMENT_ID = f.DEPARTMENT_ID
 );
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT COUNT(*) INTO v_resultado FROM vw_acima_media_depto;
  v_resultado := 'Funcionarios acima da media do dept: ' || v_resultado;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
