-- Questao 02: View com self-join - gerente

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_funcionarios_gerente';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_funcionarios_gerente AS
SELECT f.EMPLOYEE_ID,
       f.FIRST_NAME || ' ' || f.LAST_NAME AS funcionario,
       g.FIRST_NAME || ' ' || g.LAST_NAME AS gerente
  FROM FUNCIONARIOS f
  LEFT JOIN FUNCIONARIOS g ON g.EMPLOYEE_ID = f.MANAGER_ID;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT funcionario || ' -> ' || NVL(gerente, 'Sem gerente') INTO v_resultado
    FROM vw_funcionarios_gerente WHERE EMPLOYEE_ID = 100;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
