-- Question 04: Aggregated view by department

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP VIEW vw_salary_por_depto';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE OR REPLACE VIEW vw_salary_por_depto AS
SELECT DEPARTMENT_ID,
       SUM(SALARY) AS total_salary,
       ROUND(AVG(SALARY), 2) AS media_salary,
       COUNT(*) AS qtd_funcionarios
  FROM FUNCIONARIOS
 GROUP BY DEPARTMENT_ID;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESULTADO_DEMO PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE RESULTADO_DEMO (RESULTADO VARCHAR2(4000));

DECLARE
  v_resultado VARCHAR2(4000);
BEGIN
  SELECT 'Dept ' || DEPARTMENT_ID || ' total ' || total_salary INTO v_resultado
    FROM vw_salary_por_depto WHERE DEPARTMENT_ID = 60;
  DELETE FROM RESULTADO_DEMO;
  INSERT INTO RESULTADO_DEMO VALUES (v_resultado);
  DBMS_OUTPUT.PUT_LINE(v_resultado);
END;
/

SELECT RESULTADO FROM RESULTADO_DEMO;
