-- Questao 07: Processamento em lote (BULK COLLECT/FORALL)

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_reajuste_lote_q07';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;

CREATE OR REPLACE PROCEDURE sp_reajuste_lote_q07 (
  p_percentual IN NUMBER DEFAULT 5
) IS
  TYPE t_ids IS TABLE OF FUNCIONARIOS.EMPLOYEE_ID%TYPE;
  v_ids t_ids;
BEGIN
  SELECT EMPLOYEE_ID
    BULK COLLECT INTO v_ids
    FROM FUNCIONARIOS;

  FORALL i IN 1 .. v_ids.COUNT
    UPDATE FUNCIONARIOS
       SET SALARY = SALARY * (1 + (p_percentual / 100))
     WHERE EMPLOYEE_ID = v_ids(i);

  DBMS_OUTPUT.PUT_LINE('Reajuste aplicado a ' || SQL%ROWCOUNT || ' funcionarios.');
  ROLLBACK;
END;
/

SET SERVEROUTPUT ON;

BEGIN
  sp_reajuste_lote_q07(5);
END;
/
