-- Questao 03: EXECUTE IMMEDIATE

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_contar_tabela_q03';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE PROCEDURE sp_contar_tabela_q03 (
  p_nome_tabela IN VARCHAR2,
  p_total       OUT NUMBER
) IS
  v_sql VARCHAR2(200);
BEGIN
  IF p_nome_tabela NOT IN ('FUNCIONARIOS', 'PEDIDOS') THEN
    RAISE_APPLICATION_ERROR(-20003, 'Tabela nao permitida: ' || p_nome_tabela);
  END IF;

  v_sql := 'SELECT COUNT(*) FROM ' || p_nome_tabela;
  EXECUTE IMMEDIATE v_sql INTO p_total;
END;
/

SET SERVEROUTPUT ON;

DECLARE
  v_total NUMBER;
BEGIN
  sp_contar_tabela_q03('FUNCIONARIOS', v_total);
  DBMS_OUTPUT.PUT_LINE('FUNCIONARIOS: ' || v_total);

  sp_contar_tabela_q03('PEDIDOS', v_total);
  DBMS_OUTPUT.PUT_LINE('PEDIDOS: ' || v_total);
END;
/
