-- Questao 01: Controle transacional

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_transacao_q01';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE PROCEDURE sp_transacao_q01 IS
BEGIN
  UPDATE FUNCIONARIOS
     SET SALARY = SALARY + 100
   WHERE EMPLOYEE_ID = 100;

  INSERT INTO PEDIDOS (
    ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID,
    ORDER_STATUS, ORDER_TOTAL, SALES_REP_ID
  ) VALUES (
    99987, SYSDATE, 'direct', 101, 0, 1500, 153
  );

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Transacao concluida com COMMIT.');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Erro na transacao. ROLLBACK executado: ' || SQLERRM);
END;
/

SET SERVEROUTPUT ON;

BEGIN
  sp_transacao_q01;
  ROLLBACK;
END;
/
