-- Questao 10: Uso de SAVEPOINT

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_savepoint_q10';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FUNCIONARIOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FUNCIONARIOS AS SELECT * FROM HR.EMPLOYEES;
CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE OR REPLACE PROCEDURE sp_savepoint_q10 IS
  v_salary_antes FUNCIONARIOS.SALARY%TYPE;
  v_salary_depois FUNCIONARIOS.SALARY%TYPE;
BEGIN
  SELECT SALARY INTO v_salary_antes FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 100;

  UPDATE FUNCIONARIOS
     SET SALARY = SALARY + 100
   WHERE EMPLOYEE_ID = 100;

  SAVEPOINT antes_etapa_arriscada;

  BEGIN
    UPDATE PEDIDOS
       SET ORDER_TOTAL = 'INVALIDO'
     WHERE ORDER_ID = 2459;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK TO SAVEPOINT antes_etapa_arriscada;
      DBMS_OUTPUT.PUT_LINE('Etapa arriscada revertida via SAVEPOINT.');
  END;

  SELECT SALARY INTO v_salary_depois FROM FUNCIONARIOS WHERE EMPLOYEE_ID = 100;

  DBMS_OUTPUT.PUT_LINE(
    'Salario antes: ' || v_salary_antes || ' | Salario depois: ' || v_salary_depois
  );

  ROLLBACK;
END;
/

SET SERVEROUTPUT ON;

BEGIN
  sp_savepoint_q10;
END;
/
