-- Questao 06: Agendamento com DBMS_SCHEDULER

BEGIN
  EXECUTE IMMEDIATE 'DROP PROCEDURE sp_arquivar_pedidos_q06';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS_ARQUIVO_Q06';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PEDIDOS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  DBMS_SCHEDULER.DROP_JOB('JOB_ARQUIVAR_PEDIDOS_Q06', TRUE);
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PEDIDOS AS SELECT * FROM OE.ORDERS;

CREATE TABLE PEDIDOS_ARQUIVO_Q06 AS
SELECT * FROM PEDIDOS WHERE 1 = 0;

CREATE OR REPLACE PROCEDURE sp_arquivar_pedidos_q06 (
  p_data_limite IN DATE DEFAULT ADD_MONTHS(SYSDATE, -12)
) IS
BEGIN
  INSERT INTO PEDIDOS_ARQUIVO_Q06
  SELECT *
    FROM PEDIDOS
   WHERE ORDER_DATE < p_data_limite;

  DELETE FROM PEDIDOS
   WHERE ORDER_DATE < p_data_limite;

  COMMIT;
END;
/

BEGIN
  DBMS_SCHEDULER.CREATE_JOB(
    job_name        => 'JOB_ARQUIVAR_PEDIDOS_Q06',
    job_type        => 'STORED_PROCEDURE',
    job_action      => 'SP_ARQUIVAR_PEDIDOS_Q06',
    start_date      => SYSTIMESTAMP,
    repeat_interval => 'FREQ=DAILY; BYHOUR=2; BYMINUTE=0; BYSECOND=0',
    enabled         => FALSE,
    comments        => 'Arquiva pedidos antigos diariamente as 2h'
  );
END;
/

SELECT job_name, enabled, repeat_interval
  FROM user_scheduler_jobs
 WHERE job_name = 'JOB_ARQUIVAR_PEDIDOS_Q06';
